### ISSUE TITLE
Fannovel updated/depricated Preprocessers v 1

### ISSUE THREAD

**Issue by Duemellon** [shockz0rz/ComfyUI_InterpolateEverything#1]
github.com/Fannovel16/comfy_controlnet_preprocessors has the notice:
**THIS REPO IS ARCHVIED. THE WIP REWORK OF IT IS https://github.com/Fannovel16/comfyui_controlnet_aux**

I removed the old version of Fannovel16 preprocessors, installed the new aux version but now getting 

_Traceback (most recent call last):
  File "E:\ComfyUI\custom_nodes\ComfyUI_InterpolateEverything\__init__.py", line 18, in <module>
    spec.loader.exec_module(comfy_controlnet_preprocessors)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\ComfyUI\\custom_nodes/comfy_controlnet_preprocessors/__init__.py'
...
...
 0.0 seconds (IMPORT FAILED): E:\ComfyUI\custom_nodes\ComfyUI_InterpolateEverything_

**Comment by Vegansaregrassfed** [comment]
Same problem. Same log.

I see someone posted a different issue two days ago, so is there a fix of a workaround for this?

**Comment by alexbofa** [comment]
Hello, the same problem. Now this note is relevant [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux). The old [comfy_controlnet_preprocessors](https://github.com/Fannovel16/comfy_controlnet_preprocessors) conflicts with others

**Comment by shockz0rz** [comment]
Merry Christmas! InterpolateEverything has (finally) been updated for compatibility with controlnet_aux. Apologies for taking so long on this.
